// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8g_x87n911T1O-VCbvGABNrJYLo0BU7c',
    appId: '1:180644345442:web:2cfd69e6103a69041e433b',
    messagingSenderId: '180644345442',
    projectId: 'intro-mobile-flutter',
    authDomain: 'intro-mobile-flutter.firebaseapp.com',
    storageBucket: 'intro-mobile-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJx4p59PESTjhOo7W3cwxWo6osnRAn8uo',
    appId: '1:180644345442:android:c053c565af7ab4cb1e433b',
    messagingSenderId: '180644345442',
    projectId: 'intro-mobile-flutter',
    storageBucket: 'intro-mobile-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb2a8mnjBPvzU_DkfRMuWnXbFd3M9TTOY',
    appId: '1:180644345442:ios:7ede45dbbb6e88491e433b',
    messagingSenderId: '180644345442',
    projectId: 'intro-mobile-flutter',
    storageBucket: 'intro-mobile-flutter.appspot.com',
    iosBundleId: 'com.example.introMobileProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAb2a8mnjBPvzU_DkfRMuWnXbFd3M9TTOY',
    appId: '1:180644345442:ios:7ede45dbbb6e88491e433b',
    messagingSenderId: '180644345442',
    projectId: 'intro-mobile-flutter',
    storageBucket: 'intro-mobile-flutter.appspot.com',
    iosBundleId: 'com.example.introMobileProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8g_x87n911T1O-VCbvGABNrJYLo0BU7c',
    appId: '1:180644345442:web:aae3db3a63dbd3a31e433b',
    messagingSenderId: '180644345442',
    projectId: 'intro-mobile-flutter',
    authDomain: 'intro-mobile-flutter.firebaseapp.com',
    storageBucket: 'intro-mobile-flutter.appspot.com',
  );
}
